// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxy8yy1xZPURMMHYfI_izZcX_lg_zlzcE',
    appId: '1:230570888778:web:fa65b72eee82de3ea4a0b3',
    messagingSenderId: '230570888778',
    projectId: 'sumobileapp-6bbeb',
    authDomain: 'sumobileapp-6bbeb.firebaseapp.com',
    storageBucket: 'sumobileapp-6bbeb.firebasestorage.app',
    measurementId: 'G-MN7HM8RZR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmeLNZumZoUSzhk8V1IyrIe8AQKrnMcp8',
    appId: '1:230570888778:android:071783c46b4d741aa4a0b3',
    messagingSenderId: '230570888778',
    projectId: 'sumobileapp-6bbeb',
    storageBucket: 'sumobileapp-6bbeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKoho6WvulPhOeLH4AcKBADAWRekO7Pno',
    appId: '1:230570888778:ios:5d0716a3708c9494a4a0b3',
    messagingSenderId: '230570888778',
    projectId: 'sumobileapp-6bbeb',
    storageBucket: 'sumobileapp-6bbeb.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKoho6WvulPhOeLH4AcKBADAWRekO7Pno',
    appId: '1:230570888778:ios:5d0716a3708c9494a4a0b3',
    messagingSenderId: '230570888778',
    projectId: 'sumobileapp-6bbeb',
    storageBucket: 'sumobileapp-6bbeb.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxy8yy1xZPURMMHYfI_izZcX_lg_zlzcE',
    appId: '1:230570888778:web:2e9715078267c0e1a4a0b3',
    messagingSenderId: '230570888778',
    projectId: 'sumobileapp-6bbeb',
    authDomain: 'sumobileapp-6bbeb.firebaseapp.com',
    storageBucket: 'sumobileapp-6bbeb.firebasestorage.app',
    measurementId: 'G-FJN0E1KPTV',
  );
}
